apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  selector:
    app: resultserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002